# Generated by Django 3.0.6 on 2020-06-30 18:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('quote', 'quote'), ('base', 'base')], max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameccxt', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('version', models.CharField(blank=True, max_length=12, null=True)),
                ('api', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('countries', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('urls', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('has', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timeframes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('credentials', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timeout', models.IntegerField(blank=True, null=True)),
                ('rate_limit', models.IntegerField(blank=True, null=True)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verbose', models.BooleanField(default=False)),
                ('enable_rate_limit', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('ok', 'ok'), ('maintenance', 'maintenance'), ('shutdown', 'shutdown'), ('error', 'error')], max_length=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'exchanges',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.FloatField(null=True)),
                ('taker', models.FloatField(null=True)),
                ('active', models.BooleanField(default=None, null=True)),
                ('margin', models.BooleanField(default=None, null=True)),
                ('swap', models.BooleanField(default=None, null=True)),
                ('future', models.BooleanField(default=None, null=True)),
                ('spot', models.BooleanField(default=None, null=True)),
                ('percentage', models.BooleanField(default=None, null=True)),
                ('symbol', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('limits', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('precision', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_base', to='marketsdata.Currency')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='marketsdata.Exchange')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_quote', to='marketsdata.Currency')),
            ],
            options={
                'verbose_name_plural': 'markets',
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange',
            field=models.ManyToManyField(related_name='currency', to='marketsdata.Exchange'),
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('cl', models.DecimalField(decimal_places=5, max_digits=20, null=True, verbose_name='close')),
                ('vo', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='volume')),
                ('ss', models.DecimalField(decimal_places=10, max_digits=20, null=True, verbose_name='synthetic short')),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candle', to='marketsdata.Exchange')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candle', to='marketsdata.Market')),
            ],
            options={
                'verbose_name_plural': 'candles',
                'ordering': ['-dt'],
                'unique_together': {('market', 'dt')},
            },
        ),
    ]
