# Generated by Django 3.0.6 on 2020-07-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='nameccxt',
            new_name='ccxt',
        ),
    ]
