# Generated by Django 3.0.6 on 2020-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0006_auto_20200701_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='bitcoin_balance',
            field=models.BooleanField(default=False),
        ),
    ]
