# Generated by Django 3.0.6 on 2020-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0007_exchange_bitcoin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='need_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
