# Generated by Django 3.0.6 on 2020-07-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0008_auto_20200706_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='need_password',
            new_name='password_auth',
        ),
    ]
