# Generated by Django 3.0.6 on 2020-07-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0009_auto_20200706_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='password',
        ),
    ]
