# Generated by Django 3.0.6 on 2020-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0010_remove_exchange_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='trade_base_currency',
            field=models.BooleanField(default=True),
        ),
    ]
