# Generated by Django 3.0.6 on 2020-07-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0012_auto_20200708_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='precision_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
