# Generated by Django 3.0.6 on 2020-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0013_exchange_precision_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='funding_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='funding_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
