# Generated by Django 3.0.6 on 2020-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0014_auto_20200711_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='funding_rate_predicted',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
