# Generated by Django 3.0.6 on 2020-07-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0015_candle_funding_rate_predicted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='funding_rate',
            new_name='perp_funding_rate',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='funding_rate_predicted',
            new_name='perp_funding_rate_predicted',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='funding_timestamp',
            new_name='perp_funding_timestamp',
        ),
    ]
