# Generated by Django 3.0.6 on 2020-07-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0016_auto_20200711_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='perp_funding_rate_predicted',
            new_name='perp_funding_rate_next',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='perp_funding_timestamp',
            new_name='perp_funding_time_next',
        ),
    ]
