# Generated by Django 3.0.6 on 2020-07-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0017_auto_20200711_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='perp_funding_rate_next',
        ),
    ]
