# Generated by Django 3.0.6 on 2020-07-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0018_remove_candle_perp_funding_rate_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='perp_funding_rate_next',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
