# Generated by Django 3.0.6 on 2020-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0019_candle_perp_funding_rate_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='fut_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='fut_listing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
