# Generated by Django 3.0.6 on 2020-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0020_auto_20200713_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='fut_basis_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
