# Generated by Django 3.0.6 on 2020-07-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0021_candle_fut_basis_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='fut_delivery',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='fut_listing',
        ),
    ]
