# Generated by Django 3.0.6 on 2020-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0022_auto_20200713_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='fut_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='fut_listing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='perp_next_funding',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
