# Generated by Django 3.0.6 on 2020-07-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0023_auto_20200713_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='perp_next_funding',
            new_name='perp_funding_time',
        ),
    ]
