# Generated by Django 3.0.6 on 2020-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0024_auto_20200713_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='fut_underlying_index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
