# Generated by Django 3.0.6 on 2020-07-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0025_candle_fut_underlying_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='perp_funding_rate_next',
            new_name='perp_funding_rate_predicted',
        ),
        migrations.RenameField(
            model_name='candle',
            old_name='perp_funding_time_next',
            new_name='perp_funding_time',
        ),
        migrations.RemoveField(
            model_name='market',
            name='perp_funding_time',
        ),
        migrations.AddField(
            model_name='candle',
            name='fut_basis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
