# Generated by Django 3.0.6 on 2020-07-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0026_auto_20200714_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='trade',
        ),
    ]
