# Generated by Django 3.0.6 on 2020-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0027_remove_exchange_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='updated',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
