# Generated by Django 3.0.6 on 2020-07-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0029_auto_20200714_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='settlement_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='marketsdata.Currency'),
        ),
    ]
