# Generated by Django 3.0.6 on 2020-07-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0030_market_settlement_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='settlement_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='marketsdata.Currency'),
        ),
    ]
