# Generated by Django 3.0.6 on 2020-07-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0031_auto_20200716_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='settlement_currency',
            new_name='settlement',
        ),
    ]
