# Generated by Django 3.0.6 on 2020-07-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0033_remove_exchange_bitcoin_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='password_auth',
        ),
    ]
