# Generated by Django 3.0.6 on 2020-07-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0034_remove_exchange_password_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='contract_value_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_contract_val', to='marketsdata.Currency'),
        ),
        migrations.AlterField(
            model_name='market',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_settlement', to='marketsdata.Currency'),
        ),
    ]
