# Generated by Django 3.0.6 on 2020-07-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0035_auto_20200716_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='contract_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='contract_value_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_contr', to='marketsdata.Currency'),
        ),
        migrations.AlterField(
            model_name='market',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_settl', to='marketsdata.Currency'),
        ),
    ]
