# Generated by Django 3.0.6 on 2020-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0036_auto_20200716_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='contract_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='maker',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='taker',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
