# Generated by Django 3.0.6 on 2020-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0037_auto_20200717_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='cl',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='ss',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='vo',
            field=models.FloatField(null=True),
        ),
    ]
