# Generated by Django 3.0.6 on 2020-07-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0038_auto_20200724_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='ask',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='bid',
            field=models.FloatField(null=True),
        ),
    ]
