# Generated by Django 3.0.6 on 2020-07-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0039_auto_20200725_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='cl',
            new_name='last',
        ),
    ]
