# Generated by Django 3.0.6 on 2020-07-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0040_auto_20200725_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='bid',
        ),
    ]
