# Generated by Django 3.0.6 on 2020-07-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0041_auto_20200726_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='updated',
        ),
    ]
