# Generated by Django 3.0.6 on 2020-08-04 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0043_auto_20200726_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
