# Generated by Django 3.0.6 on 2020-08-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0044_exchange_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quote', 'quote'), ('base', 'base')], max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currency types',
            },
        ),
    ]
