# Generated by Django 3.0.6 on 2020-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0045_currencytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencytype',
            options={'verbose_name_plural': 'Types'},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='type',
        ),
        migrations.AddField(
            model_name='currency',
            name='type',
            field=models.ManyToManyField(related_name='currency_types', to='marketsdata.CurrencyType'),
        ),
    ]
