# Generated by Django 3.0.6 on 2020-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0046_auto_20200809_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='type',
            field=models.ManyToManyField(related_name='currency', to='marketsdata.CurrencyType'),
        ),
    ]
