# Generated by Django 3.0.6 on 2020-08-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0047_auto_20200809_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='fut_listing',
            new_name='listing',
        ),
    ]
