# Generated by Django 3.0.6 on 2020-08-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0049_candle_vo24'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='vo24',
            new_name='vo_avg',
        ),
    ]
