# Generated by Django 3.0.6 on 2020-09-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0050_auto_20200812_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'get_latest_by': 'dt', 'ordering': ['-dt'], 'verbose_name_plural': 'candles'},
        ),
    ]
