# Generated by Django 3.0.6 on 2020-09-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0051_auto_20200918_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'currencies'},
        ),
    ]
