# Generated by Django 3.0.6 on 2020-09-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0052_auto_20200920_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
