# Generated by Django 3.0.6 on 2020-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0053_auto_20200921_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='short_sell',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
