# Generated by Django 3.0.6 on 2020-10-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0054_market_short_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='short_sell',
        ),
    ]
