# Generated by Django 3.0.6 on 2020-10-10 09:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0056_auto_20201009_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='order_book',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
