# Generated by Django 3.0.6 on 2020-10-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0057_market_order_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='contract_value',
            new_name='amount_min',
        ),
    ]
