# Generated by Django 3.0.6 on 2020-10-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0058_auto_20201011_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='amount_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='cost_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='cost_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='price_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='price_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
