# Generated by Django 3.0.6 on 2020-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0059_auto_20201011_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='collateral_currency',
            field=models.ManyToManyField(related_name='market_collateral', to='marketsdata.Currency'),
        ),
    ]
