# Generated by Django 3.0.6 on 2020-10-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0060_market_collateral_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='contract_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
