# Generated by Django 3.0.6 on 2020-10-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0062_orderbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='orderbook',
            new_name='data',
        ),
    ]
