# Generated by Django 3.0.6 on 2020-10-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0063_auto_20201012_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='name',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
