# Generated by Django 3.0.6 on 2020-10-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0064_orderbook_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
