# Generated by Django 3.0.6 on 2020-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0065_auto_20201012_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='orderbook_limit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
