# Generated by Django 3.0.6 on 2020-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0066_exchange_orderbook_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='type',
            field=models.CharField(choices=[('quote', 'quote'), ('base', 'base'), ('stable coin', 'stable coin')], max_length=20, null=True),
        ),
    ]
