# Generated by Django 3.0.6 on 2020-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0067_auto_20201014_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='type',
            field=models.CharField(choices=[('quote', 'quote'), ('base', 'base')], max_length=20, null=True),
        ),
    ]
