# Generated by Django 3.0.6 on 2020-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0068_auto_20201014_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='stable_coin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
