# Generated by Django 3.0.6 on 2020-10-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0069_currency_stable_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='stable_coin',
            field=models.BooleanField(default=False),
        ),
    ]
