# Generated by Django 3.0.6 on 2020-10-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0070_auto_20201014_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='credit_limit',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
