# Generated by Django 3.0.6 on 2020-10-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0071_exchange_credit_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='credit_limit',
            new_name='api_credit',
        ),
    ]
