# Generated by Django 3.0.6 on 2020-10-19 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0072_auto_20201019_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='credit',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
