# Generated by Django 3.0.6 on 2020-10-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0073_exchange_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='api_credit',
        ),
    ]
