# Generated by Django 3.0.6 on 2020-10-29 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0074_remove_exchange_api_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
