# Generated by Django 3.0.6 on 2021-02-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0076_currency_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='quotes',
        ),
        migrations.AddField(
            model_name='currency',
            name='quotes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_quotes', to='marketsdata.Exchange'),
        ),
    ]
