# Generated by Django 3.0.6 on 2021-02-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0077_auto_20210228_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='quotes',
        ),
    ]
