# Generated by Django 3.0.6 on 2021-03-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0078_remove_currency_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='ohlcv_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
