# Generated by Django 3.0.6 on 2021-03-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0079_market_ohlcv_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='ohlcv_limit',
        ),
    ]
