# Generated by Django 3.0.6 on 2021-03-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0080_remove_market_ohlcv_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='limit_ohlcv',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
