# Generated by Django 3.0.6 on 2021-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0081_exchange_limit_ohlcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='markets_type',
            field=models.CharField(blank=True, default='spot', max_length=100, null=True),
        ),
    ]
