# Generated by Django 3.0.6 on 2021-03-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0082_exchange_markets_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='markets_type',
            new_name='market_types',
        ),
    ]
