# Generated by Django 3.0.6 on 2021-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0083_auto_20210305_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('spot', 'spot'), ('future', 'future'), ('futures', 'futures'), ('swap', 'swap'), ('delivery', 'delivery'), ('', '')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.RemoveField(
            model_name='market',
            name='type',
        ),
        migrations.AddField(
            model_name='market',
            name='type',
            field=models.ManyToManyField(related_name='market', to='marketsdata.MarketTypes'),
        ),
    ]
