# Generated by Django 3.0.6 on 2021-03-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0084_auto_20210305_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketTypes',
            new_name='MarketType',
        ),
    ]
