# Generated by Django 3.0.6 on 2021-03-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0085_auto_20210305_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencytype',
            options={'verbose_name_plural': 'Currency Types'},
        ),
        migrations.AlterModelOptions(
            name='markettype',
            options={'verbose_name_plural': 'Market Types'},
        ),
    ]
