# Generated by Django 3.0.6 on 2021-03-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0086_auto_20210305_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencytype',
            options={'verbose_name_plural': 'Types (currencies)'},
        ),
        migrations.AlterModelOptions(
            name='markettype',
            options={'verbose_name_plural': 'Types (markets)'},
        ),
    ]
