# Generated by Django 3.0.6 on 2021-03-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0089_auto_20210305_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettype',
            name='type',
            field=models.CharField(choices=[('spot', 'spot'), ('future', 'future'), ('futures', 'futures'), ('swap', 'swap'), ('delivery', 'delivery'), ('', '')], max_length=20, null=True),
        ),
    ]
