# Generated by Django 3.0.6 on 2021-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0092_auto_20210305_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='market_type',
            field=models.ManyToManyField(to='marketsdata.MarketType'),
        ),
    ]
