# Generated by Django 3.0.6 on 2021-03-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0093_exchange_market_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='market_types',
        ),
    ]
