# Generated by Django 3.0.6 on 2021-03-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0094_remove_exchange_market_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='market_type',
            new_name='market_types',
        ),
    ]
