# Generated by Django 3.0.6 on 2021-03-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0095_auto_20210305_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_type', to='marketsdata.MarketType'),
        ),
    ]
