# Generated by Django 3.0.6 on 2021-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0096_auto_20210305_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='market_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency', to='marketsdata.MarketType'),
        ),
    ]
