# Generated by Django 3.0.6 on 2021-03-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0097_currency_market_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettype',
            name='type',
            field=models.CharField(blank=True, choices=[('spot', 'spot'), ('future', 'future'), ('futures', 'futures'), ('swap', 'swap'), ('delivery', 'delivery')], max_length=20, null=True),
        ),
    ]
