# Generated by Django 3.0.6 on 2021-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0099_auto_20210306_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='derivative',
            field=models.CharField(blank=True, choices=[('perpetual', 'perpetual'), ('future', 'future')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='type',
            field=models.CharField(blank=True, choices=[('spot', 'spot'), ('derivative', 'derivative')], max_length=20, null=True),
        ),
    ]
