# Generated by Django 3.0.6 on 2021-03-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0100_auto_20210306_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='delivery',
            field=models.CharField(blank=True, choices=[('quarterly', 'quarterly'), ('monthly', 'monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='contract_value_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_contract', to='marketsdata.Currency'),
        ),
        migrations.AlterField(
            model_name='market',
            name='settlement',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('COIN', 'COIN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='type',
            field=models.CharField(choices=[('spot', 'spot'), ('derivative', 'derivative')], max_length=20, null=True),
        ),
    ]
