# Generated by Django 3.0.6 on 2021-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0102_remove_market_collateral_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='type',
            field=models.CharField(blank=True, choices=[('spot', 'spot'), ('derivative', 'derivative')], max_length=20, null=True),
        ),
    ]
