# Generated by Django 3.0.6 on 2021-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0103_auto_20210306_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
