# Generated by Django 3.0.6 on 2021-03-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0104_exchange_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='type',
            new_name='ccxt_type',
        ),
    ]
