# Generated by Django 3.0.6 on 2021-03-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0106_auto_20210306_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='ccxt_type',
            new_name='type',
        ),
    ]
