# Generated by Django 3.0.6 on 2021-03-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0107_auto_20210306_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='ccxt_id',
            new_name='exid',
        ),
    ]
