# Generated by Django 3.0.6 on 2021-03-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0108_auto_20210306_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='type',
            new_name='supported_market_types',
        ),
    ]
