# Generated by Django 3.0.6 on 2021-03-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0109_auto_20210306_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='margin',
        ),
    ]
