# Generated by Django 3.0.6 on 2021-03-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0110_remove_market_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='settlement',
            new_name='margined',
        ),
    ]
