# Generated by Django 3.0.6 on 2021-03-06 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0111_auto_20210306_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_settlement', to='marketsdata.Currency'),
        ),
    ]
