# Generated by Django 3.0.6 on 2021-03-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0112_market_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='margined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_margined', to='marketsdata.Currency'),
        ),
    ]
