# Generated by Django 3.0.6 on 2021-03-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0113_auto_20210306_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='margined',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('COIN', 'COIN')], max_length=20, null=True),
        ),
    ]
