# Generated by Django 3.0.6 on 2021-03-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0114_auto_20210306_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='margined',
        ),
    ]
