# Generated by Django 3.0.6 on 2021-03-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0115_remove_market_margined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='settlement',
        ),
        migrations.AddField(
            model_name='market',
            name='margined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_margined', to='marketsdata.Currency'),
        ),
    ]
