# Generated by Django 3.0.6 on 2021-03-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0116_auto_20210306_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='fut_delivery',
            new_name='delivery_date',
        ),
    ]
