# Generated by Django 3.0.6 on 2021-03-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0117_auto_20210306_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='delivery',
        ),
    ]
