# Generated by Django 3.0.6 on 2021-03-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0118_remove_market_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='percentage',
        ),
    ]
