# Generated by Django 3.0.6 on 2021-03-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0120_auto_20210306_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='type_ccxt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
