# Generated by Django 3.0.6 on 2021-03-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0121_market_type_ccxt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='info',
            new_name='response',
        ),
    ]
