# Generated by Django 3.0.6 on 2021-03-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0122_auto_20210306_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
