# Generated by Django 3.0.6 on 2021-03-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0123_exchange_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='fut_basis',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='fut_basis_rate',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='fut_underlying_index',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='perp_funding_rate',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='perp_funding_rate_predicted',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='perp_funding_time',
        ),
    ]
