# Generated by Django 3.0.6 on 2021-03-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0124_auto_20210307_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='ss',
        ),
    ]
