# Generated by Django 3.0.6 on 2021-03-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0125_remove_candle_ss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='last',
            new_name='close',
        ),
    ]
