# Generated by Django 3.0.6 on 2021-03-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0126_auto_20210308_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='vo',
            new_name='volume',
        ),
    ]
