# Generated by Django 3.0.6 on 2021-03-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0127_auto_20210308_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='vo_avg',
            new_name='volume_avg',
        ),
    ]
