# Generated by Django 3.0.6 on 2021-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0128_auto_20210308_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
