# Generated by Django 3.0.6 on 2021-03-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0129_currency_excluded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='excluded',
        ),
    ]
