# Generated by Django 3.0.6 on 2021-03-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0130_remove_currency_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='excluded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
