# Generated by Django 3.0.6 on 2021-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0132_auto_20210312_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='ccxt_default_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
