# Generated by Django 3.0.6 on 2021-03-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0133_market_ccxt_default_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='ccxt_default_type',
            new_name='ccxt_type_default',
        ),
    ]
