# Generated by Django 3.0.6 on 2021-03-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0134_auto_20210312_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='ccxt_type',
            new_name='ccxt_type_response',
        ),
    ]
