# Generated by Django 3.0.6 on 2021-03-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0135_auto_20210312_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='ccxt_type_default',
            new_name='ccxt_type_options',
        ),
    ]
