# Generated by Django 3.0.6 on 2021-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0136_auto_20210312_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='dollar_currency',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
