# Generated by Django 3.0.6 on 2021-03-14 10:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0137_exchange_dollar_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='rate_limits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='rate_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='timeout',
            field=models.IntegerField(default=3000),
        ),
    ]
