# Generated by Django 3.0.6 on 2021-03-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0138_auto_20210314_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='supported_market_types',
            new_name='ccxt_default_types',
        ),
    ]
