# Generated by Django 3.0.6 on 2021-03-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0139_auto_20210314_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='ccxt_default_types',
            new_name='default_types',
        ),
    ]
