# Generated by Django 3.0.6 on 2021-03-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0140_auto_20210314_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='ccxt_type_options',
            new_name='default_type',
        ),
    ]
