# Generated by Django 3.0.6 on 2021-03-14 13:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0141_auto_20210314_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='credit_max_reached',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
