# Generated by Django 3.0.6 on 2021-03-14 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0142_exchange_credit_max_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='credit_max_reached',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
