# Generated by Django 3.0.6 on 2021-03-14 14:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0143_auto_20210314_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='credit_max_reached',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
