# Generated by Django 3.0.6 on 2021-03-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0144_auto_20210314_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='credit_max_reached',
            new_name='credit_max',
        ),
    ]
