# Generated by Django 3.0.6 on 2021-03-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0145_auto_20210315_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='dollar_currency',
        ),
    ]
