# Generated by Django 3.0.6 on 2021-03-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0147_currency_dollar_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='dollar_currency',
        ),
    ]
