# Generated by Django 3.0.6 on 2021-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0148_remove_currency_dollar_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='dollar_currency',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
