# Generated by Django 3.0.6 on 2021-03-25 10:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0149_exchange_dollar_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='funding_rate',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
