# Generated by Django 3.0.6 on 2021-06-08 09:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0152_auto_20210530_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='top10',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
