# Generated by Django 3.0.6 on 2021-06-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0153_market_top10'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='top',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
