# Generated by Django 3.0.6 on 2021-06-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0154_candle_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='top10',
        ),
    ]
