# Generated by Django 3.0.6 on 2021-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0155_remove_market_top10'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='top',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
