# Generated by Django 3.0.6 on 2021-06-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0156_market_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='top',
        ),
    ]
