# Generated by Django 3.0.6 on 2021-06-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0157_remove_candle_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='funding_rate_freq',
            field=models.PositiveSmallIntegerField(blank=True, default=8, null=True),
        ),
    ]
