# Generated by Django 3.0.6 on 2020-06-30 18:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketsdata', '0001_initial'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('api_secret', models.CharField(blank=True, max_length=100)),
                ('limit_order', models.BooleanField(default=True)),
                ('credentials', models.BooleanField(default=True)),
                ('limit_price_tolerance', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='marketsdata.Exchange')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='strategy.Strategy')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=150, null=True)),
                ('clientOrderId', models.CharField(max_length=150, null=True)),
                ('symbol', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(max_length=150, null=True)),
                ('side', models.CharField(max_length=150, null=True)),
                ('average', models.FloatField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('filled', models.FloatField(null=True)),
                ('remaining', models.FloatField(null=True)),
                ('api', models.BooleanField(null=True)),
                ('fee', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('trades', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('lastTradeTimestamp', models.DateTimeField(null=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('dt_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='trading.Account')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='strategy.Allocation')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='marketsdata.Market')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(null=True)),
                ('total', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('used', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('free', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dt', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='trading.Account')),
            ],
            options={
                'verbose_name_plural': 'Funds',
                'ordering': ['-dt'],
                'get_latest_by': 'dt',
            },
        ),
    ]
