# Generated by Django 3.0.6 on 2020-07-22 16:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0037_auto_20200717_0959'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'get_latest_by': 'dt_create', 'ordering': ['-dt_create'], 'verbose_name_plural': 'Funds'},
        ),
        migrations.RemoveField(
            model_name='fund',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='free',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='info',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='total',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='used',
        ),
        migrations.RemoveField(
            model_name='order',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='average',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='order',
            name='side',
        ),
        migrations.RemoveField(
            model_name='order',
            name='symbol',
        ),
        migrations.AddField(
            model_name='account',
            name='instrument',
            field=models.CharField(blank=True, choices=[('future', 'future'), ('swap', 'swap')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='marketsdata.Currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='trading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='account_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='marketsdata.Currency'),
        ),
        migrations.AddField(
            model_name='fund',
            name='dt_create',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='fund',
            name='equity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='marketsdata.Exchange'),
        ),
        migrations.AddField(
            model_name='fund',
            name='margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_val',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit_price_tolerance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='trading.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='filled',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='marketsdata.Market'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.FloatField(null=True)),
                ('liquidation_price', models.FloatField(null=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('size_available', models.CharField(max_length=10, null=True)),
                ('cost_avg', models.FloatField(null=True)),
                ('margin', models.FloatField(null=True)),
                ('margin_maint_ratio', models.FloatField(null=True)),
                ('realized_pnl', models.FloatField(null=True)),
                ('unrealized_pnl', models.FloatField(null=True)),
                ('instrument_id', models.CharField(max_length=150, null=True)),
                ('side', models.CharField(max_length=150, null=True)),
                ('margin_mode', models.CharField(max_length=150, null=True)),
                ('leverage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('dt_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='trading.Account')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='marketsdata.Exchange')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='marketsdata.Market')),
            ],
            options={
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
