# Generated by Django 3.0.6 on 2020-07-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_order_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee',
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='trading.Account'),
        ),
    ]
