# Generated by Django 3.0.6 on 2020-07-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_order_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trades',
        ),
    ]
