# Generated by Django 3.0.6 on 2020-07-22 16:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20200722_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
