# Generated by Django 3.0.6 on 2020-07-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_order_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
    ]
