# Generated by Django 3.0.6 on 2020-07-23 08:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_remove_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
