# Generated by Django 3.0.6 on 2020-07-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_position_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='sub_account_equity',
            field=models.FloatField(null=True),
        ),
    ]
