# Generated by Django 3.0.6 on 2020-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_position_sub_account_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='margin_ratio',
            field=models.FloatField(null=True),
        ),
    ]
