# Generated by Django 3.0.6 on 2020-07-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_position_margin_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='credentials',
            new_name='valid_credentials',
        ),
    ]
