# Generated by Django 3.0.6 on 2020-07-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20200726_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit_order',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='trading',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_credentials',
            field=models.BooleanField(default=None),
        ),
    ]
