# Generated by Django 3.0.6 on 2020-07-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_auto_20200726_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='valid_credentials',
            new_name='is_valid_credentials',
        ),
    ]
