# Generated by Django 3.0.6 on 2020-07-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_auto_20200726_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_valid_credentials',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
