# Generated by Django 3.0.6 on 2020-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_auto_20200727_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='limit_order',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='trading',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
