# Generated by Django 3.0.6 on 2020-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_auto_20200728_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='valid_credentials',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
