# Generated by Django 3.0.6 on 2020-07-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_auto_20200729_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='account_type',
            new_name='markets_type',
        ),
    ]
