# Generated by Django 3.0.6 on 2020-07-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_auto_20200729_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='markets_type',
        ),
    ]
