# Generated by Django 3.0.6 on 2020-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_remove_fund_markets_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='total',
            field=models.BooleanField(null=True),
        ),
    ]
