# Generated by Django 3.0.6 on 2020-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_fund_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_strategy',
            field=models.FloatField(null=True),
        ),
    ]
