# Generated by Django 3.0.6 on 2020-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_order_price_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='value_usd',
            field=models.FloatField(null=True),
        ),
    ]
