# Generated by Django 3.0.6 on 2020-08-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_position_value_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='cost_avg',
            new_name='entry_price',
        ),
    ]
