# Generated by Django 3.0.6 on 2020-09-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0033_auto_20200928_1109'),
        ('trading', '0027_auto_20200928_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='strategy.Strategy'),
        ),
    ]
