# Generated by Django 3.0.6 on 2020-10-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0053_auto_20200921_0836'),
        ('trading', '0029_auto_20200928_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.Account'),
        ),
        migrations.AlterField(
            model_name='position',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='marketsdata.Exchange'),
        ),
        migrations.AlterField(
            model_name='position',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='marketsdata.Market'),
        ),
    ]
