# Generated by Django 3.0.6 on 2020-10-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0030_auto_20201007_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
