# Generated by Django 3.0.6 on 2020-10-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_fund_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='total',
        ),
    ]
