# Generated by Django 3.0.6 on 2020-10-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0055_remove_market_short_sell'),
        ('trading', '0032_auto_20201008_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund', to='marketsdata.Currency'),
        ),
        migrations.AddField(
            model_name='fund',
            name='equity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='total',
            field=models.BooleanField(null=True),
        ),
    ]
