# Generated by Django 3.0.6 on 2020-10-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_auto_20201008_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='total',
        ),
    ]
