# Generated by Django 3.0.6 on 2020-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_remove_fund_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='margin_preference',
            field=models.CharField(blank=True, choices=[('swap', 'swap'), ('future', 'future')], max_length=20),
        ),
    ]
