# Generated by Django 3.0.6 on 2020-10-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0035_account_margin_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='markets',
        ),
    ]
