# Generated by Django 3.0.6 on 2020-10-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0055_remove_market_short_sell'),
        ('trading', '0036_remove_account_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='markets',
            field=models.ManyToManyField(blank=True, related_name='account', to='marketsdata.Market'),
        ),
    ]
