# Generated by Django 3.0.6 on 2020-10-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0055_remove_market_short_sell'),
        ('trading', '0037_account_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='marketsdata.Exchange'),
        ),
    ]
