# Generated by Django 3.0.6 on 2020-10-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0038_auto_20201008_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='markets',
        ),
    ]
