# Generated by Django 3.0.6 on 2020-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0039_remove_account_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_qty',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position_mode',
            field=models.CharField(blank=True, choices=[('dual', 'dual'), ('hedge', 'hedge')], max_length=20),
        ),
    ]
