# Generated by Django 3.0.6 on 2020-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_auto_20201009_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='instrument_preference',
            field=models.CharField(blank=True, choices=[(0, 'swap'), (1, 'future')], max_length=20),
        ),
    ]
