# Generated by Django 3.0.6 on 2020-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0042_account_instrument_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='margin_preference',
            field=models.CharField(blank=True, choices=[(0, 'USDT'), (1, 'underlying asset')], max_length=20),
        ),
    ]
