# Generated by Django 3.0.6 on 2020-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0043_auto_20201009_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='instrument_preference',
            field=models.CharField(blank=True, choices=[('swap', 'swap'), ('future', 'future')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_preference',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('underlying asset', 'underlying asset')], max_length=20),
        ),
    ]
