# Generated by Django 3.0.6 on 2020-10-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0044_auto_20201009_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='margin_preference',
            new_name='settlement_preference',
        ),
    ]
