# Generated by Django 3.0.6 on 2020-10-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0045_auto_20201009_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='settlement_preference',
            new_name='margin_preference',
        ),
    ]
