# Generated by Django 3.0.6 on 2020-10-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0046_auto_20201009_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='instrument_preference',
            field=models.CharField(blank=True, choices=[('swap', 'perpetual'), ('future', 'delivery')], max_length=20),
        ),
    ]
