# Generated by Django 3.0.6 on 2020-10-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0047_auto_20201009_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='instrument_preference',
            field=models.CharField(blank=True, choices=[('swap', 'Future (perpetual)'), ('future', 'Future (delivery)')], max_length=20),
        ),
    ]
