# Generated by Django 3.0.6 on 2020-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0048_auto_20201009_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='instrument_preference',
            field=models.CharField(blank=True, choices=[('swap', 'Future - perpetual'), ('future', 'Future - delivery')], max_length=20),
        ),
    ]
