# Generated by Django 3.0.6 on 2020-10-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0049_auto_20201009_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='instrument_preference',
            new_name='future_preference',
        ),
    ]
