# Generated by Django 3.0.6 on 2020-10-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0050_auto_20201009_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='future_preference',
            field=models.CharField(blank=True, choices=[('perp', 'perpetual'), ('fut', 'delivery')], max_length=20),
        ),
    ]
