# Generated by Django 3.0.6 on 2020-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0051_auto_20201009_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='spot_preference',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('BTC', 'BTC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_preference',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('coin', 'underlying asset')], max_length=20),
        ),
    ]
