# Generated by Django 3.0.6 on 2020-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0052_auto_20201009_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='margin_preference',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('BTC', 'BTC'), ('coin', 'underlying asset')], max_length=20),
        ),
    ]
