# Generated by Django 3.0.6 on 2020-10-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0056_auto_20201009_0904'),
        ('trading', '0053_auto_20201009_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='trading.Account'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='marketsdata.Currency'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='marketsdata.Exchange'),
        ),
    ]
