# Generated by Django 3.0.6 on 2020-10-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0054_auto_20201010_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='future_preference',
            new_name='contract_preference',
        ),
    ]
