# Generated by Django 3.0.6 on 2020-10-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0055_auto_20201011_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='margin_preference',
            new_name='contract_margin',
        ),
    ]
