# Generated by Django 3.0.6 on 2020-10-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0056_auto_20201011_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='equity',
            new_name='total',
        ),
    ]
