# Generated by Django 3.0.6 on 2020-10-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0057_auto_20201014_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='balance',
            new_name='free',
        ),
    ]
