# Generated by Django 3.0.6 on 2020-10-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0058_auto_20201014_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lastTradeTimestamp',
            new_name='last_trade_timestamp',
        ),
    ]
