# Generated by Django 3.0.6 on 2020-10-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0059_auto_20201019_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
