# Generated by Django 3.0.6 on 2020-10-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0060_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10, null=True),
        ),
    ]
