# Generated by Django 3.0.6 on 2020-10-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0061_order_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='size',
            new_name='amount',
        ),
    ]
