# Generated by Django 3.0.6 on 2020-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0062_auto_20201019_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
