# Generated by Django 3.0.6 on 2020-10-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0063_order_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_average',
            new_name='average',
        ),
    ]
