# Generated by Django 3.0.6 on 2020-10-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0065_order_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trades',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
