# Generated by Django 3.0.6 on 2020-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0066_order_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.BigIntegerField(null=True),
        ),
    ]
