# Generated by Django 3.0.6 on 2020-10-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0067_auto_20201019_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
