# Generated by Django 3.0.6 on 2020-10-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0069_order_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee',
        ),
    ]
