# Generated by Django 3.0.6 on 2020-10-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0071_order_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='used',
            field=models.FloatField(null=True),
        ),
    ]
