# Generated by Django 3.0.6 on 2021-03-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0072_fund_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='free',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='total',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='used',
        ),
    ]
