# Generated by Django 3.0.6 on 2021-03-13 16:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0073_auto_20210313_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='free',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='total',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='used',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
