# Generated by Django 3.0.6 on 2021-03-13 17:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0075_auto_20210313_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='balance',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
