# Generated by Django 3.0.6 on 2021-03-14 08:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0076_fund_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='derivative',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
