# Generated by Django 3.0.6 on 2021-03-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0077_fund_derivative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='contract_preference',
            new_name='derivative',
        ),
    ]
