# Generated by Django 3.0.6 on 2021-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0078_auto_20210314_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='derivative',
            field=models.CharField(blank=True, choices=[('perpetual', 'perpetual'), ('delivery', 'delivery')], max_length=20),
        ),
    ]
