# Generated by Django 3.0.6 on 2021-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0079_auto_20210314_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='spot_preference',
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('spot', 'spot'), ('derivative', 'derivative')], max_length=20),
        ),
    ]
