# Generated by Django 3.0.6 on 2021-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0081_auto_20210314_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='margined',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('BTC', 'BTC'), ('coin', 'underlying asset')], max_length=20, null=True),
        ),
    ]
