# Generated by Django 3.0.6 on 2021-03-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0137_exchange_dollar_currency'),
        ('trading', '0083_remove_account_margined'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='margined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_margined', to='marketsdata.Currency'),
        ),
    ]
