# Generated by Django 3.0.6 on 2021-03-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0084_account_margined'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_qty',
            field=models.FloatField(null=True),
        ),
    ]
