# Generated by Django 3.0.6 on 2021-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0085_position_max_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='size_available',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
