# Generated by Django 3.0.6 on 2021-03-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0086_auto_20210314_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='margin_mode',
            field=models.CharField(choices=[('isolated', 'isolated'), ('crossed', 'crossed')], max_length=10, null=True),
        ),
    ]
