# Generated by Django 3.0.6 on 2021-03-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0087_auto_20210315_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='leverage',
            new_name='leverage_max',
        ),
    ]
