# Generated by Django 3.0.6 on 2021-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0088_auto_20210315_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='leverage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
