# Generated by Django 3.0.6 on 2021-03-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0089_position_leverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='size_available',
        ),
        migrations.RemoveField(
            model_name='position',
            name='sub_account_equity',
        ),
    ]
