# Generated by Django 3.0.6 on 2021-03-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0090_auto_20210315_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='params',
        ),
    ]
