# Generated by Django 3.0.6 on 2021-03-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0091_remove_order_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='api',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contract_val',
        ),
    ]
