# Generated by Django 3.0.6 on 2021-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0092_auto_20210315_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clientOrderId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.AlterField(
            model_name='account',
            name='limit_order',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='trading',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='leverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_strategy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
