# Generated by Django 3.0.6 on 2021-03-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0093_auto_20210320_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='leverage',
        ),
    ]
