# Generated by Django 3.0.6 on 2021-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0094_remove_order_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
