# Generated by Django 3.0.6 on 2021-03-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0095_order_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderId',
            new_name='orderid',
        ),
    ]
