# Generated by Django 3.0.6 on 2021-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0096_auto_20210321_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lev',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
