# Generated by Django 3.0.6 on 2021-03-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0097_account_lev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='lev',
            new_name='leverage',
        ),
    ]
