# Generated by Django 3.0.6 on 2021-03-27 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0098_auto_20210327_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='limited_integer_field',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
