# Generated by Django 3.0.6 on 2021-03-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0099_account_limited_integer_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='leverage',
        ),
    ]
