# Generated by Django 3.0.6 on 2021-03-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0100_remove_account_leverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='limited_integer_field',
            new_name='leverage',
        ),
    ]
