# Generated by Django 3.0.6 on 2021-04-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0101_auto_20210327_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
