# Generated by Django 3.0.6 on 2021-05-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0102_order_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
