# Generated by Django 3.0.6 on 2021-05-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0105_auto_20210506_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='owner',
            new_name='user',
        ),
    ]
