# Generated by Django 3.0.6 on 2021-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0106_auto_20210506_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
