# Generated by Django 3.0.6 on 2021-05-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0107_order_route_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='size_cont',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
