# Generated by Django 3.0.6 on 2021-05-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0108_position_size_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reduce_only',
            field=models.BooleanField(default=False),
        ),
    ]
