# Generated by Django 3.0.6 on 2021-05-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0109_order_reduce_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reduce_only',
        ),
    ]
