# Generated by Django 3.0.6 on 2021-05-26 14:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0110_remove_order_reduce_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
