# Generated by Django 3.0.6 on 2021-05-27 14:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0112_remove_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
