# Generated by Django 3.0.6 on 2021-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0113_order_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='filled',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='max_qty',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
