# Generated by Django 3.0.6 on 2021-05-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0114_auto_20210527_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trades',
        ),
    ]
