# Generated by Django 3.0.6 on 2021-05-27 16:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0115_remove_order_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trades',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
