# Generated by Django 3.0.6 on 2021-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0116_order_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='hedge',
            field=models.FloatField(null=True),
        ),
    ]
