# Generated by Django 3.0.6 on 2021-05-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0150_market_funding_rate'),
        ('trading', '0117_position_hedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='marketsdata.Currency'),
        ),
    ]
