# Generated by Django 3.0.6 on 2021-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0118_position_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='size',
        ),
        migrations.AddField(
            model_name='position',
            name='value',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
