# Generated by Django 3.0.6 on 2021-05-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0121_auto_20210530_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='size_cont',
            new_name='size',
        ),
    ]
