# Generated by Django 3.0.6 on 2021-05-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0150_market_funding_rate'),
        ('trading', '0122_auto_20210530_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_asset', to='marketsdata.Currency'),
        ),
        migrations.AlterField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_unit', to='marketsdata.Currency'),
        ),
    ]
