# Generated by Django 3.0.6 on 2021-05-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0123_auto_20210530_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='value',
            new_name='asset_value',
        ),
    ]
