# Generated by Django 3.0.6 on 2021-05-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0124_auto_20210530_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='position',
            name='asset_value',
        ),
    ]
