# Generated by Django 3.0.6 on 2021-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0125_auto_20210530_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='leverage_max',
            field=models.IntegerField(null=True),
        ),
    ]
