# Generated by Django 3.0.6 on 2021-05-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0126_auto_20210531_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='derivative',
            new_name='margin_assets',
        ),
    ]
