# Generated by Django 3.0.6 on 2021-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0127_auto_20210531_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='initial_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='maint_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='order_initial_margin',
            field=models.FloatField(null=True),
        ),
    ]
