# Generated by Django 3.0.6 on 2021-05-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0128_auto_20210531_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='margin_maint_ratio',
        ),
    ]
