# Generated by Django 3.0.6 on 2021-05-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0129_remove_position_margin_maint_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='margin',
            new_name='margin_balance',
        ),
    ]
