# Generated by Django 3.0.6 on 2021-05-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0152_auto_20210530_1213'),
        ('trading', '0131_auto_20210531_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='notional',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='underlying_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='marketsdata.Currency'),
        ),
    ]
