# Generated by Django 3.0.6 on 2021-05-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0132_auto_20210531_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='notional',
            new_name='notional_value',
        ),
    ]
