# Generated by Django 3.0.6 on 2021-06-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0133_auto_20210531_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='leverage',
        ),
    ]
