# Generated by Django 3.0.6 on 2021-06-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0134_remove_position_leverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='leverage_max',
            new_name='leverage',
        ),
    ]
