# Generated by Django 3.0.6 on 2021-06-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0152_auto_20210530_1213'),
        ('trading', '0135_auto_20210602_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='unit',
        ),
        migrations.AddField(
            model_name='position',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_asset', to='marketsdata.Currency'),
        ),
    ]
