# Generated by Django 3.0.6 on 2021-06-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0136_auto_20210602_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='underlying_asset',
            new_name='settlement',
        ),
    ]
