# Generated by Django 3.0.6 on 2021-06-04 10:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0137_auto_20210602_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='positions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
