# Generated by Django 3.0.6 on 2021-06-05 09:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketsdata', '0152_auto_20210530_1213'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0138_fund_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dt_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_wallet', models.CharField(max_length=50, null=True)),
                ('to_wallet', models.CharField(max_length=50, null=True)),
                ('transferid', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=None, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('timestamp', models.IntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='trading.Account')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='marketsdata.Currency')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='marketsdata.Exchange')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
