# Generated by Django 3.0.6 on 2021-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0139_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='timestamp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transferid',
            field=models.BigIntegerField(null=True),
        ),
    ]
