# Generated by Django 3.0.6 on 2021-06-07 18:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0140_auto_20210605_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
