# Generated by Django 3.0.6 on 2021-06-07 19:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0141_order_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='segment',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
