# Generated by Django 3.0.6 on 2021-06-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0142_order_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='segment',
            new_name='segments',
        ),
    ]
