# Generated by Django 3.0.6 on 2021-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0143_auto_20210607_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated',
            field=models.BooleanField(null=True),
        ),
    ]
