# Generated by Django 3.0.6 on 2021-06-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0144_account_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='derivative',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='position_mode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
