# Generated by Django 3.0.6 on 2021-06-16 08:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0145_auto_20210610_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='response_2',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
