# Generated by Django 3.0.6 on 2021-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0146_position_response_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
